### ISSUE TITLE
gsctl should handle multiple API endpoints as contexts

### ISSUE THREAD

**Issue by marians** [giantswarm/gsctl#47]
Story: As a user, I want to stay logged in while using more than one API endpoint, so that I can quickly switch between installations (contexts).

Currently a config file stores only one `email` and `token`. This forces users to log in every time when switching to a different API endpoint using the `--api-endpoint` flag.

We could instead store the endpoint-specific context information like this:

```yaml
endpoints:
  "https://api.giantswarm.io":
    token: ecb96eeb-3e16-4c04-8673-fb600bc36882
    email: marian@giantswarm.io
    organization: ""
    cluster: ""
updated: 2017-04-20T10:28:08+02:00
```

This would allow to easily keep login data for any number of endpoints.
